apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: localsecrets  
spec:
  type: secretstores.local.file
  version: v1
  metadata:
    - name: secretsFile
      value: C:/Work/Dapr/gab-2021-dapr/src/BuildingBlocks/Building-Blocks-Secret-Cli/Components/secrets.json
    - name: nestedSeparator
      value: ":"
