apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: azurekeyvault  
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
    - name: vaultName
      value: ntkkv
    - name: azureTenantId
      value: "eda6cdbb-7f74-4f2b-acc7-86b50cd3f8a7"
    - name: azureClientId
      value: "befe9c36-bf5c-4bdf-9203-7c2acc160f3f"
    - name: azureClientSecret
      value : "PE4rsGOPC+hPrd2KrfkF6ee1aDy26jIb6xH5eviN"