apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: azurekeyvault  
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
    - name: vaultName
      value: KEYVAULTNAME
    - name: azureTenantId
      value: "TENANTID"
    - name: azureClientId
      value: "CLIENTID"
    - name: azureClientSecret
      value : "CLIENTSECRET"
